"""accounts, profiles, resumes and interview history

Revision ID: ee1633ec7576
Revises: 
Create Date: 2026-09-28 13:47:25.354421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee1633ec7576'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('consent_data', sa.Boolean(), nullable=False),
    sa.Column('consent_training', sa.Boolean(), nullable=False),
    sa.Column('consent_version', sa.String(length=20), nullable=False),
    sa.Column('consented_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('parsed_profile', sa.JSON(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resumes_user_id'), ['user_id'], unique=False)

    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('class10_board', sa.String(length=100), nullable=False),
    sa.Column('class10_score', sa.Float(), nullable=False),
    sa.Column('class10_score_type', sa.String(length=12), nullable=False),
    sa.Column('class10_year', sa.Integer(), nullable=False),
    sa.Column('higher_secondary_type', sa.String(length=10), nullable=False),
    sa.Column('higher_secondary_board', sa.String(length=150), nullable=False),
    sa.Column('higher_secondary_score', sa.Float(), nullable=False),
    sa.Column('higher_secondary_score_type', sa.String(length=12), nullable=False),
    sa.Column('higher_secondary_year', sa.Integer(), nullable=False),
    sa.Column('college', sa.String(length=200), nullable=False),
    sa.Column('degree', sa.String(length=100), nullable=False),
    sa.Column('branch', sa.String(length=100), nullable=False),
    sa.Column('cgpa', sa.Float(), nullable=False),
    sa.Column('cgpa_scale', sa.Float(), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('interview_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=True),
    sa.Column('session_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('overall_grade', sa.String(length=20), nullable=True),
    sa.Column('questions_answered', sa.Integer(), nullable=False),
    sa.Column('evaluator_name', sa.String(length=100), nullable=True),
    sa.Column('evaluator_version', sa.String(length=50), nullable=True),
    sa.Column('integrity', sa.JSON(), nullable=True),
    sa.Column('attention_metrics', sa.JSON(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('session_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('family', sa.String(length=50), nullable=True),
    sa.Column('reasoning_type', sa.String(length=50), nullable=True),
    sa.Column('project_reference', sa.String(length=300), nullable=True),
    sa.Column('source_id', sa.String(length=300), nullable=True),
    sa.Column('is_followup', sa.Boolean(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('evaluation', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'turn_number')
    )
    with op.batch_alter_table('session_turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_turns_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_turns_session_id'))

    op.drop_table('session_turns')
    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_sessions_user_id'))

    op.drop_table('interview_sessions')
    op.drop_table('student_profiles')
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resumes_user_id'))

    op.drop_table('resumes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
