"""session last activity time

Revision ID: eeeb3959ae84
Revises: ee1633ec7576
Create Date: 2026-09-28 14:22:06.250577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeeb3959ae84'
down_revision = 'ee1633ec7576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_activity_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.drop_column('last_activity_at')

    # ### end Alembic commands ###
